In [10]:
import cv2
import numpy as np
import face_recognition
import os
from datetime import datetime
import matplotlib.pyplot as plt

In [11]:
path = 'C:/Users/ANUSKA RAY/Downloads/ImagesAttendance'
images = []
classNames = []
myList = os.listdir(path)
print(myList)
for cl in myList:
    curImg = cv2.imread(f'{path}/{cl}')
    images.append(curImg)
    classNames.append(os.path.splitext(cl)[0])
print(classNames)

['Anuska_Ray.jpg', 'Ekta Rani.jpg', 'Shivani Rakesh.jpg']
['Anuska_Ray', 'Ekta Rani', 'Shivani Rakesh']


In [12]:
def findEncodings(images) : 
    encodeList = []
    for img in images:
        img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
        encode = face_recognition.face_encodings(img)[0]
        encodeList.append(encode)
    return encodeList

In [13]:
encodeListKnown = findEncodings(images)
#print(len(encodeListKnown))
print("Encoding complete")

Encoding complete


In [14]:
with open('C:/Users/ANUSKA RAY/Downloads/Attendance.csv', 'w+') as f:
    pass

In [15]:
def markAttendance(name) : 
    with open('C:/Users/ANUSKA RAY/Downloads/Attendance.csv', 'r+') as f:
        myDataList = f.readlines()
        nameList = []
        print(myDataList)
        for line in myDataList:
            entry = line.split(',')
            nameList.append(entry[0])
        if name not in nameList:
            now = datetime.now()
            dtString = now.strftime("%H:%M:%S")
            f.writelines(f'\n{name}, {dtString}')

In [16]:
cap = cv2.VideoCapture(0)

In [17]:
#c = 0 ;
while True:
    #c = c + 1
    success, img = cap.read()
    imgs = cv2.resize(img, (0,0), None, 0.25, 0.25)
    imgs = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
    
    #state the location of face detect
    facesCurFrame = face_recognition.face_locations(imgs)
    #encoding the webcam images
    encodesCurFrame = face_recognition.face_encodings(imgs,facesCurFrame)
    
    for encodeFace,faceLoc in zip(encodesCurFrame,facesCurFrame):
        matches = face_recognition.compare_faces(encodeListKnown,encodeFace)
        faceDis = face_recognition.face_distance(encodeListKnown,encodeFace)
        print(faceDis)
        matchIndex = np.argmin(faceDis)
        
        if matches[matchIndex]: 
            name = classNames[matchIndex].upper()
            print(name)
            y1, x2, y2, x1 = faceLoc
            #y1, x2, y2, x1 = y1*2, x2*2, y2*2, x1*2
            print(y1, x2, y2, x1)
            cv2.rectangle(img, (x1, y1), (x2, y2), (0, 255, 0), 2)
            cv2.rectangle(img, (x1, y2-35), (x2, y2), (0, 255, 0), cv2.FILLED)
            cv2.putText(img, name, (x1 + 6, y2 - 6), cv2.FONT_HERSHEY_COMPLEX, 1, (255, 255, 255), 2)
        
    cv2.imshow('Webcam', img)
    #cv2.waitKey(1)
    #k = cv2.waitKey(1) & 0xFF == ord('q'):
    if cv2.waitKey(1) & 0xFF == ord('q'): 
        break
    
cap.release()
cv2.destroyAllWindows() 

[0.41266468 0.68937599 0.62380441]
ANUSKA_RAY
253 356 408 201
[0.45229663 0.68505796 0.57904845]
ANUSKA_RAY
253 356 408 201
[0.45347347 0.69890101 0.62278879]
ANUSKA_RAY
253 356 408 201
[0.42707654 0.66794621 0.57389735]
ANUSKA_RAY
236 356 391 201
[0.47624026 0.72067483 0.66626487]
ANUSKA_RAY
236 356 391 201
[0.43718467 0.65782113 0.58614713]
ANUSKA_RAY
236 373 391 218
[0.44435204 0.65226621 0.58751208]
ANUSKA_RAY
236 373 391 218
[0.41393034 0.67276236 0.61353992]
ANUSKA_RAY
236 373 391 218
[0.41488915 0.6837101  0.59114589]
ANUSKA_RAY
253 373 408 218
[0.41615642 0.67623029 0.55678446]
ANUSKA_RAY
236 373 391 218
[0.38967407 0.66603047 0.58085538]
ANUSKA_RAY
236 373 391 218
