In [1]:
import cv2
import numpy as np
import face_recognition
import os
from datetime import datetime
import matplotlib.pyplot as plt

In [2]:
path = 'C:/Users/ANUSKA RAY/Downloads/ImagesAttendance'
images = []
classNames = []
myList = os.listdir(path)
print(myList)
for cl in myList:
    curImg = cv2.imread(f'{path}/{cl}')
    images.append(curImg)
    classNames.append(os.path.splitext(cl)[0])
print(classNames)

['Anuska_Ray.jpg', 'Ekta Rani.jpg', 'Shivani Rakesh.jpg']
['Anuska_Ray', 'Ekta Rani', 'Shivani Rakesh']


In [3]:
def findEncodings(images) : 
    encodeList = []
    for img in images:
        img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
        encode = face_recognition.face_encodings(img)[0]
        encodeList.append(encode)
    return encodeList

In [4]:
encodeListKnown = findEncodings(images)
#print(len(encodeListKnown))
print("Encoding complete")

Encoding complete


In [5]:
with open('C:/Users/ANUSKA RAY/Downloads/Attendance.csv', 'w+') as f:
    pass

In [6]:
def markAttendance(name) : 
    with open('C:/Users/ANUSKA RAY/Downloads/Attendance.csv', 'r+') as f:
        myDataList = f.readlines()
        nameList = []
        print(myDataList)
        for line in myDataList:
            entry = line.split(',')
            nameList.append(entry[0])
        if name not in nameList:
            now = datetime.now()
            dtString = now.strftime("%H:%M:%S")
            f.writelines(f'\n{name}, {dtString}')

In [7]:
cap = cv2.VideoCapture(0)

In [8]:
#c = 0 ;
while True:
    #c = c + 1
    success, img = cap.read()
    imgs = cv2.resize(img, (0,0), None, 0.25, 0.25)
    imgs = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
    
    #state the location of face detect
    facesCurFrame = face_recognition.face_locations(imgs)
    #encoding the webcam images
    encodesCurFrame = face_recognition.face_encodings(imgs,facesCurFrame)
    
    for encodeFace,faceLoc in zip(encodesCurFrame,facesCurFrame):
        matches = face_recognition.compare_faces(encodeListKnown,encodeFace)
        faceDis = face_recognition.face_distance(encodeListKnown,encodeFace)
        print(faceDis)
        matchIndex = np.argmin(faceDis)
        
        if matches[matchIndex]: 
            name = classNames[matchIndex].upper()
            print(name)
            y1, x2, y2, x1 = faceLoc
            y1, x2, y2, x1 = y1*4, x2*4, y2*4, x1*4
            cv2.rectangle(img, (x1, y1), (x2, y2), (255, 255, 0), 20)
            cv2.rectangle(img, (x1, y2-35), (x2, y2), (0, 255, 0), cv2.FILLED)
            cv2.putText(img, name, (x1 + 6, y2 - 6), cv2.FONT_HERSHEY_COMPLEX, 1, (255, 255, 255), 2)
        
    cv2.imshow('Webcam', img)
    #cv2.waitKey(1)
    k = cv2.waitKey(30) & 0xff
    if k == 27: 
        break
    
cap.release()
cv2.destroyAllWindows() 

[0.54859721 0.70024158 0.68050907]
ANUSKA_RAY
[0.52850936 0.7339212  0.65888101]
ANUSKA_RAY
[0.55340328 0.74129702 0.64662879]
ANUSKA_RAY
[0.48291618 0.71503712 0.65783189]
ANUSKA_RAY
[0.4856438  0.69716717 0.63100584]
ANUSKA_RAY
[0.49428831 0.67154474 0.61320176]
ANUSKA_RAY
[0.48442076 0.68451122 0.5949915 ]
ANUSKA_RAY
[0.51056924 0.71533516 0.5982845 ]
ANUSKA_RAY
[0.58836977 0.68326055 0.57957099]
SHIVANI RAKESH
[0.57159035 0.72232096 0.55497256]
SHIVANI RAKESH
[0.58829551 0.71831071 0.59982675]
ANUSKA_RAY
[0.55588384 0.67408445 0.62531331]
ANUSKA_RAY
[0.55300061 0.68363254 0.64621301]
ANUSKA_RAY
[0.57316537 0.68827755 0.6712519 ]
ANUSKA_RAY
[0.53509653 0.6976443  0.64968196]
ANUSKA_RAY
[0.53022785 0.67694177 0.60226307]
ANUSKA_RAY
[0.53445934 0.72811861 0.62098843]
ANUSKA_RAY
[0.53757023 0.69217166 0.59996693]
ANUSKA_RAY
[0.57885488 0.73495043 0.61821917]
ANUSKA_RAY
[0.52390739 0.68890023 0.59930136]
ANUSKA_RAY
[0.54290235 0.73869134 0.62418709]
ANUSKA_RAY
[0.52170612 0.71489869 0.5

KeyboardInterrupt: 

In [9]:
cap.release()
cv2.destroyAllWindows()